// Generated from the interface strings: Spanish (the source language) → English.
// Keys may hold {0}, {1}… for text that varies; see core/i18n.ts.
export const EN: ReadonlyArray<readonly [string, string]> = [
  ["no se está ejecutando dentro de Coucou", "not running inside Coucou"],
  ["Falta conectar Claude Code", "Claude Code needs connecting"],
  ["revisión pedida", "review requested"],
  ["CI fallando", "CI failing"],
  ["PR de Copilot", "Copilot PR"],
  ["PRs de Copilot", "Copilot PRs"],
  ["Ejecuta", "Runs"],
  ["Lee", "Reads"],
  ["Escribe", "Writes"],
  ["Modifica", "Edits"],
  ["Busca", "Searches"],
  ["Busca texto", "Searches text"],
  ["Busca en la web", "Searches the web"],
  ["Descarga", "Downloads"],
  ["Tareas", "Tasks"],
  ["Agente", "Agent"],
  ["Lista", "Lists"],
  ["⚠ falló", "⚠ failed"],
  ["{0} terminó", "{0} finished"],
  ["{0} se detuvo por un error", "{0} stopped with an error"],
  ["+ subagente", "+ subagent"],
  ["• subagente listo", "• subagent done"],
  ["✓ Permitido siempre · {0}", "✓ Always allowed · {0}"],
  ["Claude Code pide permiso", "Claude Code asks for permission"],
  ["Claude Code tiene una pregunta", "Claude Code has a question"],
  ["Abrir {0} en VS Code", "Open {0} in VS Code"],
  ["Lo último", "Last project"],
  ["Abre una terminal en el proyecto con claude --continue", "Opens a terminal in the project with claude --continue"],
  ["Continuar donde lo dejé →", "Continue where I left off →"],
  ["Pendiente", "Pending"],
  ["Claude Code conectado", "Claude Code connected"],
  ["Hooks de una versión anterior: actualízalos en la sección Claude Code, más abajo.", "Hooks from an older version: update them in the Claude Code section, below."],
  ["Las sesiones, los permisos y las preguntas aparecen en la isla.", "Sessions, permissions and questions show up in the island."],
  ["Claude Code está en este PC, pero Coucou aún no está conectado: usa “Instalar hooks…” en la sección Claude Code, más abajo.", "Claude Code is on this PC, but Coucou is not connected yet: use “Install hooks…” in the Claude Code section, below."],
  ["Instala los hooks (sección Claude Code, más abajo) para ver tus sesiones en la isla.", "Install the hooks (Claude Code section, below) to see your sessions in the island."],
  ["Conectado: tiene su propio pill.", "Connected: it has its own pill."],
  ["Encontrado en este PC pero sin conectar: usa “Conectar…” en Agentes, más abajo.", "Found on this PC but not connected: use “Connect…” in Agents, below."],
  ["Token guardado: tus pull requests, revisiones pedidas, CI y el trabajo de GitHub Copilot aparecen en el pill de GitHub.", "Token saved: your pull requests, review requests, CI and GitHub Copilot's work appear in the GitHub pill."],
  ["Crea un token (uno clásico con “repo”, o uno de acceso fino con lectura de pull requests, estados de commits y metadatos) y pégalo en Integraciones → GitHub. El mismo token cubre Copilot.", "Create a token (a classic one with “repo”, or a fine-grained one with read access to pull requests, commit statuses and metadata) and paste it in Integrations → GitHub. The same token covers Copilot."],
  ["Crear token", "Create token"],
  ["Chat con {0}", "Chat with {0}"],
  ["Clave guardada en el Administrador de credenciales de Windows.", "Key saved in the Windows Credential Manager."],
  ["Pega tu clave en Proveedor de chat.", "Paste your key in Chat provider."],
  ["Pega tu clave de la API de Anthropic en Claude, o elige otro proveedor (DEVMARK AI, Gemini, Groq) en Proveedor de chat.", "Paste your Anthropic API key under Claude, or pick another provider (DEVMARK AI, Gemini, Groq) in Chat provider."],
  ["Tu nombre", "Your name"],
  ["Mochi te saluda como “{0}”.", "Mochi greets you as “{0}”."],
  ["Detectado: “{0}”. Puedes cambiarlo en Personalización.", "Detected: “{0}”. You can change it in Personalization."],
  ["Indícalo en Personalización para que Mochi pueda saludarte.", "Set it in Personalization so Mochi can greet you."],
  ["Uso del plan (opcional)", "Plan usage (optional)"],
  ["El relay está instalado.", "The relay is installed."],
  ["Instala el relay en Uso del plan para ver cuánto te queda del plan de Claude.", "Install the relay in Plan usage to see how much of your Claude plan is left."],
  ["Configuración", "Setup"],
  ["Qué está listo y qué falta, según los programas de este equipo.", "What is ready and what is missing, based on the programs on this computer."],
  ["Detectado en este PC", "Detected on this PC"],
  ["Añade los hooks de Coucou a ~/.gemini/settings.json, para que las sesiones de Gemini CLI aparezcan en su pill.", "Adds Coucou's hooks to ~/.gemini/settings.json so Gemini CLI sessions show up in its pill."],
  ["No se encontró Gemini CLI en este PC. Aun así puedes conectarlo para cuando lo instales.", "Gemini CLI was not found on this PC. You can still connect it for when you install it."],
  ["Añade un pequeño plugin (coucou.js) a ~/.config/opencode/plugins. No necesita nada más.", "Adds a small plugin (coucou.js) to ~/.config/opencode/plugins. Nothing else needed."],
  ["No se encontró OpenCode en este PC. Aun así puedes conectarlo para cuando lo instales.", "OpenCode was not found on this PC. You can still connect it for when you install it."],
  ["Su pill muestra tus proyectos recientes y funciona sin conectar nada. Conectarlo añade un bloque a tu perfil de PowerShell que actúa solo dentro de la terminal de VS Code: cuando termina un comando que tardó 10 segundos o más, el pill (y una notificación) te dice si salió bien. Las demás terminales quedan exactamente como están.", "Its pill shows your recent projects and works without connecting anything. Connecting adds a block to your PowerShell profile that acts only inside VS Code's terminal: when a command that took 10 seconds or more finishes, the pill (and a notification) tells you whether it went well. Other terminals stay exactly as they are."],
  ["No se encontró VS Code en este PC.", "VS Code was not found on this PC."],
  ["Cada agente tiene su propio pill junto a Mochi ({0}/{1} pills en uso). Conectar uno modifica un archivo de esa herramienta, con vista previa antes.", "Each agent has its own pill next to Mochi ({0}/{1} pills in use). Connecting one modifies a file of that tool, with a preview first."],
  ["Conectado", "Connected"],
  ["Sin conectar", "Not connected"],
  ["Reconectar…", "Reconnect…"],
  ["Conectar…", "Connect…"],
  ["Desconectar…", "Disconnect…"],
  ["Volver", "Back"],
  ["Esto es exactamente lo que cambiará. Todo lo demás de esos archivos queda intacto.", "This is exactly what will change. Everything else in those files stays untouched."],
  ["Esto solo quita la parte de Coucou. Todo lo demás de esos archivos queda intacto.", "This only removes Coucou's part. Everything else in those files stays untouched."],
  ["Copia de seguridad → {0}", "Backup → {0}"],
  ["Guardar copia y escribir", "Save backup and write"],
  ["Guardar copia y quitar", "Save backup and remove"],
  ["Conectado. Inicia una sesión nueva en esa herramienta para verla en su pill.", "Connected. Start a new session in that tool to see it in its pill."],
  ["No se pudo escribir: {0}", "Could not write: {0}"],
  ["Cancelar", "Cancel"],
  ["Agentes", "Agents"],
  ["Usar el detectado", "Use the detected one"],
  ["No se pudo detectar ningún nombre", "No name could be detected"],
  ["Automático (idioma del sistema)", "Automatic (system language)"],
  ["Personalización", "Personalization"],
  ["Al iniciar, Mochi te saluda por tu nombre, con la hora del día y la fecha de hoy.", "On start, Mochi greets you by name, with the time of day and today's date."],
  ["Saludar", "Greet me"],
  ["Saludo", "Greeting"],
  ["{name} se reemplaza por tu nombre. Ejemplo: ¡Hola {name}, bienvenido!", "{name} is replaced by your name. Example: Hello {name}, welcome!"],
  ["Idioma", "Language"],
  ["Pill inicial", "Start pill"],
  ["El pill que se muestra primero al abrir la isla.", "The pill shown first when the island opens."],
  ["Lo último y pendientes", "Last project and pending"],
  ["en la bienvenida: tu último proyecto y lo que espera (revisiones, CI)", "on the welcome: your last project and what is waiting (reviews, CI)"],
  ["Coucou está conectado a tus sesiones de Claude Code. Las herramientas, las preguntas y las peticiones de permiso aparecen en la isla, y puedes responderlas ahí.", "Coucou is connected to your Claude Code sessions. Tools, questions and permission requests show up in the island, and you can answer them there."],
  ["Instala los hooks para ver tus sesiones de Claude Code en la isla y aprobar permisos sin dejar lo que estás haciendo.", "Install the hooks to see your Claude Code sessions in the island and approve permissions without leaving what you're doing."],
  ["coucou-hook.exe aún no está en su sitio. Reinicia Coucou; si sigue fallando, compílalo con `cargo build -p coucou-hook`.", "coucou-hook.exe is not in place yet. Restart Coucou; if it keeps failing, build it with `cargo build -p coucou-hook`."],
  ["Hooks desactualizados: actualízalos para responder las preguntas de Claude desde la isla.", "Outdated hooks: update them to answer Claude's questions from the island."],
  ["Instalar hooks…", "Install hooks…"],
  ["Actualizar hooks…", "Update hooks…"],
  ["Reinstalar hooks…", "Reinstall hooks…"],
  ["El relay aún no está instalado.", "The relay is not installed yet."],
  ["Desinstalar hooks…", "Uninstall hooks…"],
  ["Esto es exactamente lo que cambiará en tu settings.json. Tus propios hooks quedan intactos.", "This is exactly what will change in your settings.json. Your own hooks stay untouched."],
  ["Esto solo quita las entradas de Coucou. Tus propios hooks quedan intactos.", "This only removes Coucou's entries. Your own hooks stay untouched."],
  ["Listo. La configuración anterior quedó guardada como {0}. Abre una sesión nueva de Claude Code para que tome los hooks.", "Done. Your previous configuration was saved as {0}. Open a new Claude Code session so it picks up the hooks."],
  ["Uso del plan", "Plan usage"],
  ["Un pequeño pill en la cabecera de la isla con lo que llevas gastado de tu plan de Claude (ventanas de 5 horas y 7 días). Claude Code solo lo informa en los planes Pro y Max.", "A small pill in the island's header with how much of your Claude plan you have used (5-hour and 7-day windows). Claude Code only reports it on the Pro and Max plans."],
  ["Mostrar en la isla", "Show in the island"],
  ["Instalado", "Installed"],
  ["Sin instalar", "Not installed"],
  ["Reinstalar relay…", "Reinstall relay…"],
  ["Instalar relay…", "Install relay…"],
  ["Desinstalar relay…", "Uninstall relay…"],
  ["Esto es exactamente lo que cambiará en tu settings.json. Si ya tienes una línea de estado, sigue funcionando igual que antes.", "This is exactly what will change in your settings.json. If you already have a status line, it keeps working as before."],
  ["Esto quita el relay de línea de estado de Coucou y devuelve la tuya, si tenías una.", "This removes Coucou's status line relay and gives yours back, if you had one."],
  ["Listo. La configuración anterior quedó guardada como {0}. El medidor aparece tras la siguiente respuesta en una sesión de Claude Code.", "Done. Your previous configuration was saved as {0}. The gauge appears after the next reply in a Claude Code session."],
  ["Siempre permitido", "Always allowed"],
  ["Peticiones que elegiste permitir siempre con el botón “Siempre”. Se responden sin preguntar y cada una aparece en el ticker de la isla. Quita una para que vuelva a preguntarte.", "Requests you chose to always allow with the “Always” button. They are answered without asking and each one shows in the island's ticker. Remove one to be asked again."],
  ["Aún no hay nada.", "Nothing here yet."],
  ["Quitar", "Remove"],
  ["No se pudo quitar: {0}", "Could not remove: {0}"],
  ["DEVMARK AI (privada)", "DEVMARK AI (private)"],
  ["IA privada de la empresa (compatible con OpenAI, https://ai.devmarkpe.com). Solo lee texto, responde un mensaje a la vez y la primera respuesta puede tardar.", "The company's private AI (OpenAI-compatible, https://ai.devmarkpe.com). It reads text only, answers one message at a time and the first answer can take a while."],
  ["Gemini, de Google AI Studio. Lee texto y código. La clave se crea gratis en Google AI Studio. Si un modelo no existe, “Probar conexión” muestra los que tu clave puede usar.", "Gemini, from Google AI Studio. Reads text and code. The key is created for free in Google AI Studio. If a model does not exist, “Test connection” shows the ones your key can use."],
  ["Groq: respuestas muy rápidas con modelos abiertos (Llama y otros). Lee texto y código. Crea una clave en la consola de Groq; “Probar conexión” muestra los modelos disponibles.", "Groq: very fast answers with open models (Llama and others). Reads text and code. Create a key in the Groq console; “Test connection” shows the available models."],
  ["Guardar clave", "Save key"],
  ["Aún no hay clave: pega la que te dieron.", "No key yet: paste the one you were given."],
  ["••••••••••••  (guardada)", "••••••••••••  (saved)"],
  ["Guardada. Nunca toca el disco ni la página.", "Saved. It never touches the disk or the page."],
  ["No se pudo guardar: {0}", "Could not save: {0}"],
  ["Clave eliminada.", "Key removed."],
  ["Probar conexión", "Test connection"],
  ["Probando…", "Testing…"],
  ["Clave API", "API key"],
  ["Conseguir una clave", "Get a key"],
  ["Modelo", "Model"],
  ["Respuesta máx.", "Max reply"],
  ["Proveedor de chat", "Chat provider"],
  ["Quién responde cuando le preguntas algo a Mochi. Al cambiarlo empieza una conversación nueva.", "Who answers when you ask Mochi something. Changing it starts a new conversation."],
  ["Responde con", "Answers with"],
  ["Aún no hay clave: el chat necesita una.", "No key yet: the chat needs one."],
  ["Guardada. Nunca toca el disco.", "Saved. It never touches the disk."],
  ["Clave secreta", "Secret key"],
  ["Token de integración", "Integration token"],
  ["Elige hasta {0} pills para mostrar junto a Mochi ({1}/{2} en uso). Las claves se guardan en el Administrador de credenciales de Windows, nunca en disco.", "Pick up to {0} pills to show next to Mochi ({1}/{2} in use). Keys are saved in the Windows Credential Manager, never on disk."],
  ["••••••••  (guardada)", "••••••••  (saved)"],
  ["Guardar", "Save"],
  ["Integraciones", "Integrations"],
  ["Pantalla principal", "Main screen"],
  ["Pantalla donde está el cursor", "Screen where the cursor is"],
  ["Sonido", "Sound"],
  ["Cierre automático", "Auto-close"],
  ["segundos después de que sales de la isla", "seconds after you leave the island"],
  ["La isla vive en", "The island lives on"],
  ["Iniciar con Windows", "Start with Windows"],
  ["Notificaciones de Windows", "Windows notifications"],
  ["un aviso cuando Claude te necesita o termina con la isla cerrada", "a notice when Claude needs you or finishes while the island is closed"],
  ["Atajos globales", "Global shortcuts"],
  ["Ctrl+Alt+Y permitir · Ctrl+Alt+N denegar (solo mientras hay una petición) · Ctrl+Alt+C abrir o cerrar", "Ctrl+Alt+Y allow · Ctrl+Alt+N deny (only while a request is up) · Ctrl+Alt+C open or close"],
  ["Sin telemetría. Las peticiones de red solo van a los servicios que tú configures.", "No telemetry. Network requests only go to the services you configure."],
  ["Suelta tus archivos aquí", "Drop your files here"],
  ["Imágenes", "Images"],
  ["Código", "Code"],
  ["Subiendo {0}", "Uploading {0}"],
  ["{0} está listo.", "{0} is ready."],
  ["¿Qué quieres hacer con él?", "What do you want to do with it?"],
  ["Preguntar sobre él", "Ask about it"],
  ["Pregúntame lo que quieras…", "Ask me anything…"],
  ["Enviar", "Send"],
  ["Continúa…", "Continues…"],
  ["Abrir en VS Code", "Open in VS Code"],
  ["Cambios", "Changes"],
  ["Esos cambios ya no están en memoria.", "Those changes are no longer in memory."],
  ["Cambios demasiado grandes", "Changes too large"],
  ["Hooks sin instalar", "Hooks not installed"],
  ["Clave sin configurar", "Key not set"],
  ["Conectado · esperando actividad", "Connected · waiting for activity"],
  ["Conectado · cargando…", "Connected · loading…"],
  ["Abrir Visual Studio Code", "Open Visual Studio Code"],
  ["Abrir {0}", "Open {0}"],
  ["Actualizar", "Refresh"],
  ["Ajustes…", "Settings…"],
  ["Integración", "Integration"],
  ["Instala el CLI de Antigravity (agy) desde antigravity.google", "Install the Antigravity CLI (agy) from antigravity.google"],
  ["No encuentro «{0}». {1}", "I can't find “{0}”. {1}"],
  ["No encuentro el programa de {0}. Instálalo o usa «En terminal».", "I can't find the {0} program. Install it or use “In terminal”."],
  ["El uso aparece al instalar el relay del plan", "Usage appears once the plan relay is installed"],
  ["Aún no hay proyectos", "No projects yet"],
  ["Abrir Claude Code", "Open Claude Code"],
  ["Continuar", "Continue"],
  ["claude --continue en el último proyecto", "claude --continue in the last project"],
  ["Abrir app", "Open app"],
  ["El programa OpenCode de Windows", "The OpenCode program for Windows"],
  ["Abrir Gemini web", "Open Gemini web"],
  ["Gemini no tiene programa de escritorio: abre gemini.google.com", "Gemini has no desktop program: opens gemini.google.com"],
  ["Abrir {0} en {1}", "Open {0} in {1}"],
  ["Elige un proyecto para empezar", "Pick a project to start"],
  ["En terminal", "In terminal"],
  ["{0} en una terminal nueva", "{0} in a new terminal"],
  ["{0} --continue en {1}", "{0} --continue in {1}"],
  ["El programa Antigravity de escritorio", "The Antigravity desktop program"],
  ["El CLI de Antigravity en una terminal nueva", "The Antigravity CLI in a new terminal"],
  ["Claude Code corre aquí", "Claude Code runs here"],
  ["Terminal conectada", "Terminal connected"],
  ["Proyectos", "Projects"],
  ["No hay proyectos recientes", "No recent projects"],
  ["Abrir VS Code", "Open VS Code"],
  ["Conectar terminal…", "Connect terminal…"],
  ["Detalles", "Details"],
  ["Despliegues", "Deployments"],
  ["Listo", "Done"],
  ["Cancelado", "Canceled"],
  ["hace {0}", "{0} ago"],
  ["Despliegue", "Deployment"],
  ["Correos", "Emails"],
  ["Revisiones pedidas", "Review requests"],
  ["Mis pull requests", "My pull requests"],
  ["+ subagente", "221"],
  ["Cargando pull requests…", "Loading pull requests…"],
  ["Repositorios", "Repositories"],
  ["Copilot · revisó {0} tuyos", "Copilot · reviewed {0} of yours"],
  ["Pull requests de Copilot", "Copilot pull requests"],
  [" (borrador)", " (draft)"],
  ["Borrador · {0}", "Draft · {0}"],
  ["Nada por aquí", "Nothing here"],
  ["{0} más en GitHub", "{0} more on GitHub"],
  ["Pago", "Payment"],
  ["Pagos", "Payments"],
  ["Sin título", "Untitled"],
  ["Recientes", "Recent"],
  ["No hay llamadas programadas", "No scheduled calls"],
  ["Reunión", "Meeting"],
  ["Agenda", "Calendar"],
  ["Se reinicia en {0}", "Resets in {0}"],
  ["Plan de Claude", "Claude plan"],
  ["Ventana de 5 horas", "5-hour window"],
  ["Ventana de 7 días", "7-day window"],
  ["Responde en tu terminal: esta no espera a Coucou.", "Answer in your terminal: this one doesn't wait for Coucou."],
  ["Otra respuesta…", "Another answer…"],
  ["Siguiente", "Next"],
  ["Responder en la terminal", "Answer in the terminal"],
  ["pregunta · {0}", "question · {0}"],
  ["Claude Code hace una pregunta", "Claude Code asks a question"],
  ["Claude necesita una respuesta.", "Claude needs an answer."],
  ["Archivo", "File"],
  ["Hacer una pregunta", "Ask a question"],
  [" está listo.", " is ready."],
  ["Resumen", "Summary"],
  ["Preguntar", "Ask"],
  ["Soltar archivo", "Drop file"],
  ["Ajustes", "Settings"],
  ["Silenciar", "Mute"],
  ["Uso del plan de Claude", "Claude plan usage"],
  ["Abrir", "Open"],
  ["Claude Code pide permiso", "258"],
  ["No hay nada en marcha ahora.", "Nothing is running right now."],
  ["Suelta un archivo o una ventana, o pregúntame lo que quieras.", "Drop a file or a window, or ask me anything."],
  ["Preguntar a Claude", "Ask Claude"],
  ["Siempre", "Always"],
  ["Permitir siempre: {0}", "Always allow: {0}"],
  ["Denegar", "Deny"],
  ["Permitir", "Allow"],
  ["El flujo se detuvo.", "The workflow stopped."],
  ["Reintentar", "Retry"],
  ["Abrir terminal", "Open terminal"],
  ["Algo salió mal.", "Something went wrong."],
  ["Se detuvo por un error.", "It stopped with an error."],
  ["La sesión se detuvo por un error.", "The session stopped with an error."],
  ["Sin más detalles.", "No further details."],
  ["terminó", "finished"],
  ["Claude Code terminó", "Claude Code finished"],
  ["Sesión terminada", "Session finished"],
  ["Demasiados toques a la vez.", "Too many pokes at once."],
  ["Dame un segundo: vuelvo al trabajo en tres segundos.", "Give me a second: I'm back to work in three seconds."],
  ["Cierre automático · {0}s", "Auto-close · {0}s"],
  ["El envío por correo no está en esta versión.", "Sending by email is not in this version."],
  ["Claude está buscando…", "Claude is searching…"],
  ["Resultado", "Result"],
];
